// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.grpc.grpcserver.server;

public interface GreetingOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.grpc.grpcserver.server.Greeting)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
