// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.grpc.grpcserver.server;

/**
 * <pre>
 * *
 * 声明接口
 * </pre>
 * <p>
 * Protobuf service {@code com.grpc.grpcserver.server.HelloWorldService}
 */
public abstract class HelloWorldService
        implements com.google.protobuf.Service {
    protected HelloWorldService() {
    }

    public static com.google.protobuf.Service newReflectiveService(
            final Interface impl) {
        return new HelloWorldService() {
            @java.lang.Override
            public void sayHello(
                    com.google.protobuf.RpcController controller,
                    com.grpc.grpcserver.server.Person request,
                    com.google.protobuf.RpcCallback<com.grpc.grpcserver.server.Greeting> done) {
                impl.sayHello(controller, request, done);
            }

        };
    }

    public static com.google.protobuf.BlockingService
    newReflectiveBlockingService(final BlockingInterface impl) {
        return new com.google.protobuf.BlockingService() {
            public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public final com.google.protobuf.Message callBlockingMethod(
                    com.google.protobuf.Descriptors.MethodDescriptor method,
                    com.google.protobuf.RpcController controller,
                    com.google.protobuf.Message request)
                    throws com.google.protobuf.ServiceException {
                if (method.getService() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "Service.callBlockingMethod() given method descriptor for " +
                                    "wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return impl.sayHello(controller, (com.grpc.grpcserver.server.Person) request);
                    default:
                        throw new java.lang.AssertionError("Can't get here.");
                }
            }

            public final com.google.protobuf.Message
            getRequestPrototype(
                    com.google.protobuf.Descriptors.MethodDescriptor method) {
                if (method.getService() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "Service.getRequestPrototype() given method " +
                                    "descriptor for wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return com.grpc.grpcserver.server.Person.getDefaultInstance();
                    default:
                        throw new java.lang.AssertionError("Can't get here.");
                }
            }

            public final com.google.protobuf.Message
            getResponsePrototype(
                    com.google.protobuf.Descriptors.MethodDescriptor method) {
                if (method.getService() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "Service.getResponsePrototype() given method " +
                                    "descriptor for wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return com.grpc.grpcserver.server.Greeting.getDefaultInstance();
                    default:
                        throw new java.lang.AssertionError("Can't get here.");
                }
            }

        };
    }

    public static final com.google.protobuf.Descriptors.ServiceDescriptor
    getDescriptor() {
        return com.grpc.grpcserver.server.HelloWorld.getDescriptor().getServices().get(0);
    }

    public static Stub newStub(
            com.google.protobuf.RpcChannel channel) {
        return new Stub(channel);
    }

    public static BlockingInterface newBlockingStub(
            com.google.protobuf.BlockingRpcChannel channel) {
        return new BlockingStub(channel);
    }

    /**
     * <code>rpc sayHello(.com.grpc.grpcserver.server.Person) returns (.com.grpc.grpcserver.server.Greeting);</code>
     */
    public abstract void sayHello(
            com.google.protobuf.RpcController controller,
            com.grpc.grpcserver.server.Person request,
            com.google.protobuf.RpcCallback<com.grpc.grpcserver.server.Greeting> done);

    public final com.google.protobuf.Descriptors.ServiceDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    public final void callMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request,
            com.google.protobuf.RpcCallback<
                    com.google.protobuf.Message> done) {
        if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "Service.callMethod() given method descriptor for wrong " +
                            "service type.");
        }
        switch (method.getIndex()) {
            case 0:
                this.sayHello(controller, (com.grpc.grpcserver.server.Person) request,
                        com.google.protobuf.RpcUtil.<com.grpc.grpcserver.server.Greeting>specializeCallback(
                                done));
                return;
            default:
                throw new java.lang.AssertionError("Can't get here.");
        }
    }

    public final com.google.protobuf.Message
    getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "Service.getRequestPrototype() given method " +
                            "descriptor for wrong service type.");
        }
        switch (method.getIndex()) {
            case 0:
                return com.grpc.grpcserver.server.Person.getDefaultInstance();
            default:
                throw new java.lang.AssertionError("Can't get here.");
        }
    }

    public final com.google.protobuf.Message
    getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "Service.getResponsePrototype() given method " +
                            "descriptor for wrong service type.");
        }
        switch (method.getIndex()) {
            case 0:
                return com.grpc.grpcserver.server.Greeting.getDefaultInstance();
            default:
                throw new java.lang.AssertionError("Can't get here.");
        }
    }

    public interface Interface {
        /**
         * <code>rpc sayHello(.com.grpc.grpcserver.server.Person) returns (.com.grpc.grpcserver.server.Greeting);</code>
         */
        public abstract void sayHello(
                com.google.protobuf.RpcController controller,
                com.grpc.grpcserver.server.Person request,
                com.google.protobuf.RpcCallback<com.grpc.grpcserver.server.Greeting> done);

    }

    public interface BlockingInterface {
        public com.grpc.grpcserver.server.Greeting sayHello(
                com.google.protobuf.RpcController controller,
                com.grpc.grpcserver.server.Person request)
                throws com.google.protobuf.ServiceException;
    }

    public static final class Stub extends com.grpc.grpcserver.server.HelloWorldService implements Interface {
        private final com.google.protobuf.RpcChannel channel;

        private Stub(com.google.protobuf.RpcChannel channel) {
            this.channel = channel;
        }

        public com.google.protobuf.RpcChannel getChannel() {
            return channel;
        }

        public void sayHello(
                com.google.protobuf.RpcController controller,
                com.grpc.grpcserver.server.Person request,
                com.google.protobuf.RpcCallback<com.grpc.grpcserver.server.Greeting> done) {
            channel.callMethod(
                    getDescriptor().getMethods().get(0),
                    controller,
                    request,
                    com.grpc.grpcserver.server.Greeting.getDefaultInstance(),
                    com.google.protobuf.RpcUtil.generalizeCallback(
                            done,
                            com.grpc.grpcserver.server.Greeting.class,
                            com.grpc.grpcserver.server.Greeting.getDefaultInstance()));
        }
    }

    private static final class BlockingStub implements BlockingInterface {
        private final com.google.protobuf.BlockingRpcChannel channel;

        private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
            this.channel = channel;
        }

        public com.grpc.grpcserver.server.Greeting sayHello(
                com.google.protobuf.RpcController controller,
                com.grpc.grpcserver.server.Person request)
                throws com.google.protobuf.ServiceException {
            return (com.grpc.grpcserver.server.Greeting) channel.callBlockingMethod(
                    getDescriptor().getMethods().get(0),
                    controller,
                    request,
                    com.grpc.grpcserver.server.Greeting.getDefaultInstance());
        }

    }

    // @@protoc_insertion_point(class_scope:com.grpc.grpcserver.server.HelloWorldService)
}

