// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamTest.proto

package com.example.test.stream.service;

/**
 * Protobuf type {@code com.example.test.stream.service.Request}
 */
public final class Request extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.example.test.stream.service.Request)
        RequestOrBuilder {
    public static final int REQUEST_FIELD_NUMBER = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    public static final int A_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.example.test.stream.service.Request)
    private static final com.example.test.stream.service.Request DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Request>
            PARSER = new com.google.protobuf.AbstractParser<Request>() {
        @java.lang.Override
        public Request parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Request(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.example.test.stream.service.Request();
    }

    private volatile java.lang.Object request_;
    private long timestamp_;
    private com.google.protobuf.LazyStringList a_;
    private byte memoizedIsInitialized = -1;

    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Request() {
        request_ = "";
        a_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    private Request(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        request_ = s;
                        break;
                    }
                    case 16: {

                        timestamp_ = input.readInt64();
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            a_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        a_.add(s);
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                a_ = a_.getUnmodifiableView();
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.example.test.stream.service.StreamTest.internal_static_com_example_test_stream_service_Request_descriptor;
    }

    public static com.example.test.stream.service.Request parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.test.stream.service.Request parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.test.stream.service.Request parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.test.stream.service.Request parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.test.stream.service.Request parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.test.stream.service.Request parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.test.stream.service.Request parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.example.test.stream.service.Request parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.test.stream.service.Request parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.test.stream.service.Request parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.test.stream.service.Request parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.example.test.stream.service.Request parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.example.test.stream.service.Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.example.test.stream.service.Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.example.test.stream.service.StreamTest.internal_static_com_example_test_stream_service_Request_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.example.test.stream.service.Request.class, com.example.test.stream.service.Request.Builder.class);
    }

    /**
     * <code>string request = 1;</code>
     *
     * @return The request.
     */
    @java.lang.Override
    public java.lang.String getRequest() {
        java.lang.Object ref = request_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            request_ = s;
            return s;
        }
    }

    /**
     * <code>string request = 1;</code>
     *
     * @return The bytes for request.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getRequestBytes() {
        java.lang.Object ref = request_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            request_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
        return timestamp_;
    }

    /**
     * <code>repeated string a = 3;</code>
     *
     * @return A list containing the a.
     */
    public com.google.protobuf.ProtocolStringList
    getAList() {
        return a_;
    }

    /**
     * <code>repeated string a = 3;</code>
     *
     * @return The count of a.
     */
    public int getACount() {
        return a_.size();
    }

    /**
     * <code>repeated string a = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The a at the given index.
     */
    public java.lang.String getA(int index) {
        return a_.get(index);
    }

    /**
     * <code>repeated string a = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the a at the given index.
     */
    public com.google.protobuf.ByteString
    getABytes(int index) {
        return a_.getByteString(index);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(request_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, request_);
        }
        if (timestamp_ != 0L) {
            output.writeInt64(2, timestamp_);
        }
        for (int i = 0; i < a_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, a_.getRaw(i));
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(request_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, request_);
        }
        if (timestamp_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(2, timestamp_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < a_.size(); i++) {
                dataSize += computeStringSizeNoTag(a_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getAList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.example.test.stream.service.Request)) {
            return super.equals(obj);
        }
        com.example.test.stream.service.Request other = (com.example.test.stream.service.Request) obj;

        if (!getRequest()
                .equals(other.getRequest())) return false;
        if (getTimestamp()
                != other.getTimestamp()) return false;
        if (!getAList()
                .equals(other.getAList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getTimestamp());
        if (getACount() > 0) {
            hash = (37 * hash) + A_FIELD_NUMBER;
            hash = (53 * hash) + getAList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.example.test.stream.service.Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.example.test.stream.service.Request}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.example.test.stream.service.Request)
            com.example.test.stream.service.RequestOrBuilder {
        private int bitField0_;
        private java.lang.Object request_ = "";
        private long timestamp_;
        private com.google.protobuf.LazyStringList a_ = com.google.protobuf.LazyStringArrayList.EMPTY;

        // Construct using com.example.test.stream.service.Request.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.test.stream.service.StreamTest.internal_static_com_example_test_stream_service_Request_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.test.stream.service.StreamTest.internal_static_com_example_test_stream_service_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.example.test.stream.service.Request.class, com.example.test.stream.service.Request.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            request_ = "";

            timestamp_ = 0L;

            a_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.example.test.stream.service.StreamTest.internal_static_com_example_test_stream_service_Request_descriptor;
        }

        @java.lang.Override
        public com.example.test.stream.service.Request getDefaultInstanceForType() {
            return com.example.test.stream.service.Request.getDefaultInstance();
        }

        @java.lang.Override
        public com.example.test.stream.service.Request build() {
            com.example.test.stream.service.Request result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.example.test.stream.service.Request buildPartial() {
            com.example.test.stream.service.Request result = new com.example.test.stream.service.Request(this);
            int from_bitField0_ = bitField0_;
            result.request_ = request_;
            result.timestamp_ = timestamp_;
            if (((bitField0_ & 0x00000001) != 0)) {
                a_ = a_.getUnmodifiableView();
                bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.a_ = a_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.example.test.stream.service.Request) {
                return mergeFrom((com.example.test.stream.service.Request) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.example.test.stream.service.Request other) {
            if (other == com.example.test.stream.service.Request.getDefaultInstance()) return this;
            if (!other.getRequest().isEmpty()) {
                request_ = other.request_;
                onChanged();
            }
            if (other.getTimestamp() != 0L) {
                setTimestamp(other.getTimestamp());
            }
            if (!other.a_.isEmpty()) {
                if (a_.isEmpty()) {
                    a_ = other.a_;
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    ensureAIsMutable();
                    a_.addAll(other.a_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.example.test.stream.service.Request parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.example.test.stream.service.Request) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>string request = 1;</code>
         *
         * @return The request.
         */
        public java.lang.String getRequest() {
            java.lang.Object ref = request_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                request_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string request = 1;</code>
         *
         * @param value The request to set.
         * @return This builder for chaining.
         */
        public Builder setRequest(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            request_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string request = 1;</code>
         *
         * @return The bytes for request.
         */
        public com.google.protobuf.ByteString
        getRequestBytes() {
            java.lang.Object ref = request_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                request_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string request = 1;</code>
         *
         * @param value The bytes for request to set.
         * @return This builder for chaining.
         */
        public Builder setRequestBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            request_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string request = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRequest() {

            request_ = getDefaultInstance().getRequest();
            onChanged();
            return this;
        }

        /**
         * <code>int64 timestamp = 2;</code>
         *
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
            return timestamp_;
        }

        /**
         * <code>int64 timestamp = 2;</code>
         *
         * @param value The timestamp to set.
         * @return This builder for chaining.
         */
        public Builder setTimestamp(long value) {

            timestamp_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 timestamp = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTimestamp() {

            timestamp_ = 0L;
            onChanged();
            return this;
        }

        private void ensureAIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                a_ = new com.google.protobuf.LazyStringArrayList(a_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @return A list containing the a.
         */
        public com.google.protobuf.ProtocolStringList
        getAList() {
            return a_.getUnmodifiableView();
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @return The count of a.
         */
        public int getACount() {
            return a_.size();
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The a at the given index.
         */
        public java.lang.String getA(int index) {
            return a_.get(index);
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the a at the given index.
         */
        public com.google.protobuf.ByteString
        getABytes(int index) {
            return a_.getByteString(index);
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @param index The index to set the value at.
         * @param value The a to set.
         * @return This builder for chaining.
         */
        public Builder setA(
                int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureAIsMutable();
            a_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @param value The a to add.
         * @return This builder for chaining.
         */
        public Builder addA(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureAIsMutable();
            a_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @param values The a to add.
         * @return This builder for chaining.
         */
        public Builder addAllA(
                java.lang.Iterable<java.lang.String> values) {
            ensureAIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, a_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearA() {
            a_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         *
         * @param value The bytes of the a to add.
         * @return This builder for chaining.
         */
        public Builder addABytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureAIsMutable();
            a_.add(value);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.example.test.stream.service.Request)
    }

}

