// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamTest.proto

package com.example.test.stream.service;

public interface RequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.example.test.stream.service.Request)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string request = 1;</code>
     *
     * @return The request.
     */
    java.lang.String getRequest();

    /**
     * <code>string request = 1;</code>
     *
     * @return The bytes for request.
     */
    com.google.protobuf.ByteString
    getRequestBytes();

    /**
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>repeated string a = 3;</code>
     *
     * @return A list containing the a.
     */
    java.util.List<java.lang.String>
    getAList();

    /**
     * <code>repeated string a = 3;</code>
     *
     * @return The count of a.
     */
    int getACount();

    /**
     * <code>repeated string a = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The a at the given index.
     */
    java.lang.String getA(int index);

    /**
     * <code>repeated string a = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the a at the given index.
     */
    com.google.protobuf.ByteString
    getABytes(int index);
}
