// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamTest.proto

package com.example.test.stream.service;

public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.example.test.stream.service.Response)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 1;</code>
     *
     * @return The response.
     */
    java.lang.String getResponse();

    /**
     * <code>string response = 1;</code>
     *
     * @return The bytes for response.
     */
    com.google.protobuf.ByteString
    getResponseBytes();

    /**
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>repeated string b = 3;</code>
     *
     * @return A list containing the b.
     */
    java.util.List<java.lang.String>
    getBList();

    /**
     * <code>repeated string b = 3;</code>
     *
     * @return The count of b.
     */
    int getBCount();

    /**
     * <code>repeated string b = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The b at the given index.
     */
    java.lang.String getB(int index);

    /**
     * <code>repeated string b = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the b at the given index.
     */
    com.google.protobuf.ByteString
    getBBytes(int index);
}
