// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamTest.proto

package com.example.test.stream.service;

public final class StreamTest {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_example_test_stream_service_Request_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_example_test_stream_service_Request_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_example_test_stream_service_Response_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_example_test_stream_service_Response_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020StreamTest.proto\022\037com.example.test.str" +
                        "eam.service\"8\n\007Request\022\017\n\007request\030\001 \001(\t\022" +
                        "\021\n\ttimestamp\030\002 \001(\003\022\t\n\001a\030\003 \003(\t\":\n\010Respons" +
                        "e\022\020\n\010response\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022\t" +
                        "\n\001b\030\003 \003(\t2\255\003\n\016TestGrpcStream\022[\n\004test\022(.c" +
                        "om.example.test.stream.service.Request\032)" +
                        ".com.example.test.stream.service.Respons" +
                        "e\022j\n\021testStreamRequest\022(.com.example.tes" +
                        "t.stream.service.Request\032).com.example.t" +
                        "est.stream.service.Response(\001\022k\n\022testStr" +
                        "eamResponse\022(.com.example.test.stream.se" +
                        "rvice.Request\032).com.example.test.stream." +
                        "service.Response0\001\022e\n\ntestStream\022(.com.e" +
                        "xample.test.stream.service.Request\032).com" +
                        ".example.test.stream.service.Response(\0010" +
                        "\001B\005P\001\210\001\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_example_test_stream_service_Request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_example_test_stream_service_Request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_example_test_stream_service_Request_descriptor,
                new java.lang.String[]{"Request", "Timestamp", "A",});
        internal_static_com_example_test_stream_service_Response_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_example_test_stream_service_Response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_example_test_stream_service_Response_descriptor,
                new java.lang.String[]{"Response", "Timestamp", "B",});
    }

    private StreamTest() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
